apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: img
data:
  PORT: "80"
  nginx.conf: |
    server {
      listen 80;
      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }
    }
