apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: img-pvc
  namespace: img
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10G
